version: "3"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: ./web
    command: npm start
    volumes:
      - ./web:/web
    ports:
      - "8000:3000"

  api:
    build: ./api
    environment: 
      - DJANGO_DEV_NAME=admin
      - DJANGO_DEV_EMAIL=hoge@example.com
      - DJANGO_DEV_PASSWORD=dev-password0
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api:/code
    ports:
      - "8001:8000"
    depends_on:
      - db
