name: Django Test CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Container and Run Tests
      run: |
        docker-compose build api
        docker-compose run api python manage.py test
