name: React Test CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Container
      run: |
        docker-compose build web
    - name: Run Tests
      run: |
        docker-compose run -e CI=true web npm test
