name: React Test CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    using: 'docker'
    image: 'web/Dockerfile'
    steps:
    - name: Run Tests
      run: |
        npm test
